project:
  type: website

website:
  title: "PREreview Champions' Handbook"
  navbar:
    left:
      - href: index.qmd
        text: "Home" 
      - text: "PREreview Champion Program"
        menu: 
          - subpages-champions-program/01-code-of-conduct.qmd.qmd
          - subpages-champions-program/02-program-expectations.qmd
          - subpages-champions-program/03-mentor-program.qmd
      - href: about-PREreview.qmd
        text: "About PREreview" 
      - href: how-to-contribute.qmd
        text: "Contribute to this Handbook"
    right:
      - icon: github
        href: https://github.com/xiuqili-xl/PREreview-Champions-Handbook-DEV


format:
  html:
    theme:
      - united
    css: styles.css
    toc: true