project:
  type: website

website:
  title: "PREreview Champions' Handbook"
  navbar:
    left:
      - href: index.qmd
        text: "The Champions' Program" 
      - href: program-description.qmd
        text: "Program Description" 
      - href: about-PREreview.qmd
        text: "About PREreview" 
      - href: how-to-contribute.qmd
        text: "Contribute to this Handbook"
    right:
      - icon: github
        href: https://github.com/xiuqili-xl/PREreview-Champions-Handbook-DEV


format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true