project:
  type: website

website:
  title: "PREreview Champions' Handbook"
  navbar:
    left:
      - href: index.qmd
        text: "Home" 
      - text: "About the Champion Program"
        menu: 
          - subpages-champions-program/01-code-of-conduct.qmd
          - subpages-champions-program/02-program-expectations.qmd
          - subpages-champions-program/03-mentor-program.qmd
      - text: "Resources"
        menu: 
          - subpages-resources/02-PREreview-resources.qmd
          - subpages-resources/03-event-planning-checklist.qmd
          - subpages-resources/04-live-review.qmd
          - subpages-resources/05-PREreview-clubs.qmd
          - subpages-resources/06-using-the-PREreview.org-website.qmd
          - subpages-resources/07-using-zoom.qmd
          - subpages-resources/08-using-Slack.qmd
          - subpages-resources/09-shared-resources.qmd
      - href: about-PREreview.qmd
        text: "About PREreview" 
      - href: how-to-contribute.qmd
        text: "Contribute to this Handbook"
    right:
      - icon: github
        href: https://github.com/xiuqili-xl/PREreview-Champions-Handbook-DEV
      - icon: linkedin
        href: https://www.linkedin.com/company/prereview
      - icon: mastodon
        href: https://mas.to/@prereview       
      - icon: bluesky
        href: https://bsky.app/profile/prereview.bsky.social    
      - icon: youtube
        href: https://www.youtube.com/@Prereview   


format:
  html:
    theme:
      - united
    css: styles.css
    toc: true
    page-layout: full