# Ways to Contribute to the Champions GitHub
There are three major ways to contribute to the Champions GitHub.

- Suggest a change, addition, or deletion to what is already on the GitHub using [Issues](https://github.com/PREreview/champions-handbook/issues).  
     - Before submitting a new issue, check to make sure a similar issue isn't already open. If one is, contribute to that issue thread with your feedback.
     - Issues labeled :sparkles:`help wanted`:sparkles:  make it easy for you to find ways you can contribute today.
     - You can also use Issues to report bugs or suggest changes.

- Become a contributor! [Fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) the repository and [make commits](https://docs.github.com/en/get-started/quickstart/contributing-to-projects#making-and-pushing-changes) to add resources and additional materials. Here are some ways you can contribute:
     - Propose a fix for a bug.
     - Suggest new content or changes to existing content for this resources.
     - Localize and translate content in this resource into languages other than English.
 
- You can send us your feedback and contributions to champions@prereview.org.

