---
title: "PREreview Resources"
---

<br/>

Here you can find a list of resources to help you in your Champions Program engagement activities. We will keep these updated regularly, so you know that you can trust the information that you share with those in your communities.

All of our resources are openly available for download on Zenodo under a CC BY 4.0 license.

<br/>

## Branding
Here you can find the [PREreview Style Guide](https://docs.google.com/document/d/1rd87SxetKbyZvSLdn-cTcQGOJMwDgugcngaPSs09m2c/edit?tab=t.0#heading=h.s1vdxhu8ko0c). Please follow these guidelines whenever possible on communications, presentations, publications, and resources.
If you have any questions or need any help styling anything, please contact our Communications and Engagement Officer, Pia Tavella, at pia@prereview.org or post in the [#PREreview Champions 2026 channel](https://prereviewcommunity.slack.com/archives/C0A8747507J) of our Community Slack instance.


<br/>

## PREreview Champions Program Badge
To claim your Open Reviewer badge, you will need to create a [Badgecraft](https://www.badgecraft.eu/) account. After verification, your PREreview badges will appear in your badge wallet. You can then share your badge through a link in Linkedin, social media (please do tag us) or on your own personal website. At the end of the Champions program, after you complete your activities, you will receive the PREreview Champions badge.

<br/>

## Workshops & Events
Peer review plays a pivotal role in determining which research projects receive funding, which findings get published, and ultimately, which knowledge is disseminated and utilized by the scientific community and the broader public. Despite its critical importance, reviewers often undergo minimal training for this crucial task. Furthermore, that training rarely focuses on mitigating the biases that are ingrained in the peer review process. Hence, new generations of reviewers often lack the frameworks to address their biases, leading to a perpetuation of the current inequities in scholarly publishing. At PREreview we offer two kinds of peer review training workshops centered on issues of equity, diversity, and inclusion: **PREreview Open Reviewers**, focused on research manuscripts’ review, and [**PREreview Open Grant Reviewers**](https://prereview.org/trainings), focused on grant applications’ review.

We work with organizations, institutions, and funding agencies that want to offer their communities the opportunity to challenge their beliefs and learn from one another how to recognize and mitigate the impact of bias in research evaluation.

Our workshops are designed for safe and inclusive delivery - both online and in-person - by providing clear guidelines ahead of time and by accommodating participants’ different communication and participation styles. Our content is intentionally interactive and is presented to participants using collaborative note-taking and other supporting tools, such as Mentimeter. Contact us at community@prereview.org to discuss which type of workshop is best for your organization and options for tailoring our workshop content for your organization’s needs.

Note: we also run 2-hour community workshops every quarter of the year which are open to individual sign-ups. Read below for more information on the next available workshop and how to register.

### PREreview Open Reviewers

The Open Reviewers Workshop is an interactive and hands-on training program designed for researchers at all career levels who are interested in engaging in ethical and constructive manuscript peer review. With a focus on promoting equity, diversity, and inclusion, the workshop provides participants with the necessary skills and knowledge to conduct constructive peer review with the use of materials from the [Open Reviewers Toolkit](https://prereview.org/resources).


### 2-hour workshop
This stand-alone introductory workshop focuses on the basics of open, preprint peer review and becoming aware of biases present in the scholarly publication process.

**Learning Objectives:**

 - A general understanding of journal-organized and independent review processes
 - An introduction to how systems of oppression manifest in the manuscript review process
 - An introduction to strategies to self-assess and mitigate bias in the context of manuscript review


### Multi-session workshops
These multi-session trainings run for  4-6 hours and offer greater opportunities for practical review experience following a structured approach to writing a review, keeping issues of bias and systemic oppression front of mind. These workshops culminate in a [Live Review session](https://prereview.org/live-reviews) facilitated by PREreview staff, where participants select and review a preprint together.

**Learning Objectives:**

 - A general understanding of journal-organized and independent review processes
 - A detailed understanding of how systems of oppression manifest in the manuscript review process
 - Strategies to self-assess and mitigate bias in the context of manuscript review
 - An in-depth understanding of and practical experience with peer reviewing a manuscript in a way that minimizes bias, striving for constructive, clear, and actionable feedback
 - An opportunity to put learning into practice by collaboratively reviewing a preprint and publishing the resulting preprint review on PREreview.org
   
We hope that after your Champions Program training, you feel adequately equipped to provide Open Reviewers training to others within your community. We list a number of resources below to help you in doing so. Please let us know if you plan on running an Open Reviewers training workshop or another relevant event for your community, and we would be happy to help you with promotion if desired.


<br/>

## The Open Reviewers Toolkit

With a focus on promoting equity, diversity, and inclusion, the [Open Reviewers Workshop](https://prereview.org/trainings) is designed for researchers at all career levels who are interested in engaging in ethical and constructive manuscript peer review. The Open Reviewers Toolkit comprises three **freely available and openly licensed guides guides** to help guide the socially-conscious and constructive composition and assessment of research manuscripts:

-The **Bias Reflection Guide** is a tool to help a reviewer assess their own biases, guiding them through a non-judgmental, self-reflective process. (Available in [English (original)](https://doi.org/10.5281/zenodo.5484051), [español](https://doi.org/10.5281/zenodo.14845399), and [português brasileiro](https://doi.org/10.5281/zenodo.17153256))
-The **Reviewer Guide** is for anyone reviewing a research manuscript. It provides a comprehensive, step-by-step framework for the reviewer to use while they are composing a review. (Available in [English (original)](https://doi.org/10.5281/zenodo.5484086), [español](https://doi.org/10.5281/zenodo.14825399), and [português brasileiro](https://doi.org/10.5281/zenodo.15496850))
-The **Review Assessment Rubric** is for anyone evaluating a research manuscript’s review. The rubric comprises 10 statements for which the evaluator is asked to provide a score and a written comment to help improve the review. (Available in [English (original)](https://doi.org/10.5281/zenodo.5484071), [español](https://doi.org/10.5281/zenodo.14845534) and [português brasileiro](https://doi.org/10.5281/zenodo.17153270))


<br/>

## Templates
Below, you can find the links to templates for the Open Reviewers workshop. These will be updated over time. Whenever using these templates, please make a copy to work from, rather than editing the template itself. Feel free to adapt these templates and the content to your audience. 

- [About PREreview](https://docs.google.com/presentation/d/1V34VTr_LJjF54mNrQM4GX-AYu1hMA1a2rP9aGGhjp8g/edit?usp=drive_link)
- [2-hour Open Reviewers workshop](https://drive.google.com/drive/folders/1NrSmGWZeKyCw0QGC9jIuS_z_ZCHpIQjX?usp=drive_link)
- [6-hour full Open Reviewers workshop](https://drive.google.com/drive/folders/1qsL34w-Z8BoEI01tWi4KOGUH2HeZT27M?usp=drive_link) 
  - [Module 1 templates](https://drive.google.com/drive/folders/1sxHEps9X2uSi0nMoZwfJ51MKQGAf73pc?usp=drive_link)
  - [Module 2 templates](https://drive.google.com/drive/folders/1xXjUvUAYm6y9VQK1lIah7QQ6LyP1MrIO?usp=drive_link)
  - [Module 3: Live Review templates](https://drive.google.com/drive/folders/1lucoGv7bMZ3ZitQpD-r6fEc_8p9SBdwl?usp=drive_link)
- Survey [pre-](https://docs.google.com/document/d/1A8U8jLUe-3m567rI4ZyxdUW0B3ypq5d8GEaI3dq2GhU/edit?usp=sharing) and [post-](https://docs.google.com/document/d/1rDKNg3Y8bvaohUlMSHsDx_H4rj_svMW0XaAZNmodJpk/edit?usp=sharing) workshop
- [Social media promotion template](https://www.canva.com/design/DAG_innxVlE/XFmJIqlN8vaMzml_Xy7L9g/view?utm_content=DAG_innxVlE&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview) (in Canva)

<br/>
