# Event planning checklist 

## 3 months before the event
  - Decide location (online or in-person)
  - Consider the format [(see some examples here](https://www.opencon.community/designing_a_satellite_event_agenda))
  - Consider what costs are involved and agree on a budget
  - Decide target audience - language, time zone, and level of knowledge 
  - Decide event dates (check what other activities are planned and any holidays to take into account)
  - Decide your content and learning objectives
  - Create promotional messaging and imagery
  - Confirm trainers and/or speakers (try to involve speakers who bring a diverse range of perspectives)
  - Confirm venue (if applicable)
  - Set up the event registration page - Gather what you need (e.g. contact details, accessibility requirements, knowledge level, location), but don’t ask for additional demographic information that you don’t need or make this optional.
  - Create a communication plan and template social media posts (translate if required)

## 1-2 months before the event
  - Send out invitation emails
  - Promote event
  - Finalize the agenda
  - Prepare presentation slide decks (translate if required)
  - Design materials and activities with the goal of collaboration, participation, and the mutual exchange of opinions and knowledge.
  - Prepare follow-up emails and pre and post-workshop surveys (translate if required)
  - Send out the pre-workshop survey (if applicable, [template here](https://drive.google.com/drive/folders/1jOSJUDvFo87ZIFkE2XH2eZL3Niz0G2H2?usp=drive_link))
  - Send out reminder emails to registrants
  - For in-person events, prepare any physical materials needed - handouts, name badges, etc. 

## During the event
  - Ensure you have a clear Code of Conduct, ways to report violations, and a follow-up procedure in place (you can find our Code of Conduct at PREreview [here](https://prereview.org/code-of-conduct))
  - Ensure audio and video set-up is working correctly
  - If you are recording the event, make sure you have asked attendees’ permission to do so.
  - Make sure you have a co-facilitator and/or a dedicated person responsible for timekeeping and handling the Q&A/chat
  - Structure notes to convey essential information in a written form that others can copy, paste, and translate, and to capture audience input.
  - Make a list of links to all the resources mentioned to be shared in the chat (makes it easier to copy and paste during your event)

## After the event
  - Post-workshop survey to be shared with attendees (if applicable, template [here](https://drive.google.com/drive/folders/1jOSJUDvFo87ZIFkE2XH2eZL3Niz0G2H2?usp=drive_link))
  - Ensure materials are openly shared, accessible, and reusable (make sure to get the relevant permissions and credit the original creator(s) before sharing) 
  - Have a call to action and provide clear ways for people to further engage
  - Submit your [engagement activity report](https://airtable.com/appGwSEmiAa0iqMFI/pagB04mtvMZW9nTCL/form)
  - Optionally, write up your event into a blog piece or article. 
  - Please refer to Module III of the PREreview Champions Program for more facilitation and planning tips from both PREreview and your fellow Champions, as well as more resources to check out. 
