# Live Reviews
Live Reviews are topic-centered, interactive preprint review calls via a video conference tool such as Zoom. Outputs from Live Reviews can be used to improve a manuscript or be integrated into journal review workflows. 

Core to PREreview's mission is increasing diversity, equity, and inclusion in scholarly peer review. Live Reviews allow structured and constructive discussions following [guided discussion questions](https://zenodo.org/records/10207527) that encourage diverse methods of participation.

## Why Live Reviews?
  - To support and empower the voices of all the experts, particularly those who have historically been excluded from the peer review process and those who are in the beginning stages of their research careers
  - To showcase a kinder, more collaborative, joyful and transparent way to provide constructive, clear and actionable feedback to preprint authors
  - To deliver this feedback to the authors and the communities who benefit from it in a timely manner
    
## Who participates?
  - Two facilitators from our team with experience in hosting Live Reviews
  - A topic expert (optional) to guide participants through a constructive discussion
  - Preprint authors (optional) to gather live feedback on their preprint
  - Researchers and experts who join from all over the world ready to collaborate on improving a preprint, build their network, and meet other experts

## What are the event outputs?
After the call, our team works with a subset of Live Review participants who contributed feedback during the call and volunteered extra time to compile the notes from the call into a PREreview that is then published on [PREreview.org](https://prereview.org/reviews) approximately two weeks after the call.

These participants have the option to be listed as review authors using either their real name or their unique PREreview pseudonym. In most cases, the review resulting from the call is integrated into the journal-organized peer review process—as it is the case for some of our collaborations with journals like JMIR Publications and Current Research in Neurobiology.

Here are all the [reviews published thus far as outputs of Live Review events](https://zenodo.org/communities/prereview-reviews/records?q=&f=resource_type%3Apublication%2Binner%3Apublication-peerreview&f=subject%3ALive%20Review&l=list&p=1&s=10&sort=newest), including those run in collaboration with JMIR Publications which are also listed in the [JMIR Publications Club](https://prereview.org/clubs/jmir-publications).

## Interested in PREreview Live Reviews?
To request our support to run a Live Review or to discuss how they can be integrated into your workflow, email us at community@prereview.org.

Current and past collaborations to host Live Reviews of preprints submitted to a journal include contracting work with [JMIR Publications](https://www.jmir.org/announcements/296) and [Current Research in Neurobiology](https://content.prereview.org/prereview-and-crneur-pilot), respectively.

## FAQs
### Who can join these events?
Anyone interested in the research topic discussed is welcome to join the call. We ask participants who contribute to the discussion and the review to state any existing competing interests according to our [code of conduct](https://prereview.org/code-of-conduct).

### Who will be at the call?
Two members of the PREreview team who will facilitate the discussion, optionally the preprint authors, optionally members of the collaborative organization co-hosting the call, and whoever has registered for the event.

### Do I have to be an active researcher to participate?
No. Anyone interested in the research topic under discussion and equipped with respect and a constructive attitude is welcome to join.

### Are the preprint authors there?
The authors of the manuscript under discussion are invited to join but their participation is optional. If they decide to join, they are asked to briefly introduce themselves and identify who they are by adding “author” to their Zoom name. The authors are encouraged to share areas of the work that they would most appreciate feedback on and allowed to observe, but are asked to remain silent until the end of the call, unless asked direct questions from the participants.

### Do I need to read the preprint in advance of the event?
Yes! Please come along having read and thought about the preprint in order to engage in meaningful discussions and evaluate collaboratively with others on the call.

### Is AI allowed in this space?
The use of AI notetaking bots or AI Chatbots, whether for generating or refining answers, is not permitted during the Live Review call. This is for two main reasons: 1. Using AI goes against the collaborative spirit of our Live Reviews and 2. At this note-taking stage of the review process, refining language is not important. If writing in English is a barrier to you, then please feel free to share your comments in your native language.

### Will the call be recorded? If so, who will have access to the video?
Often the call is recorded and in that case the video is shared solely among the stakeholders involved in organizing the call which includes the PREreview team and the collaborator.

### If I join the call, do I get to be listed as a review author?
Not necessarily. Here are your options as a participant:

1. *Join the call as a listener* - not actively contributing to the discussion
2. *Join the call only as a discussion participant* - contribute to the discussion of the manuscript by unmuting your mic when prompted by facilitators and/or by typing in your answers in the collaborative notes google doc we’ll be using during the call.
3. *Join the call as a review author* - participate in the discussion during the call and contribute to the final review that will be published on [PREreview.org](https://prereview.org/) by helping the PREreview team summarize the discussion points into a review*.

*This will likely take no more than 2 hours of your time working asynchronously on a shared google doc, and will require you creating an account on PREreview.org.

### Do I need to join with my laptop or can I join with my phone?
You can join with whatever device you have at your disposal at the time of the call, but if you had a choice, we would recommend joining with your laptop so that you can contribute to the collaborative notes document should you want to.

### How will you ensure inclusive participation?
We will have live-caption services provided via Otter.ai. Additionally, facilitators will invite vocal participation by unmuting one’s microphone when invited to speak as well as by directly adding text to a structured collaborative notes document similar to [this one](https://docs.google.com/document/d/1AQBu8Lf-L_uYxKchCoePJLHe8Ra5lBuMNbBiuPyI5Ag/edit#heading=h.vtrj59zftb3m). Finally, as for all events hosted by PREreview, participants will be asked to adhere to our [Code of Conduct](https://prereview.org/code-of-conduct).
