## PREreview Clubs

PREreview Clubs are collaborative preprint reviewing groups around a shared affiliation, affinity, interest, location, or any other common cause. Club members work together to give preprint authors timely, constructive peer feedback (sometimes via a format like our Live Reviews).

Anyone who wants to form a collaborative preprint reviewing group can ask to start a Club. While we plan to automate the process more, currently, PREreview Clubs are a concierge service. That means anyone looking to start a PREreview Club should complete this [form](https://airtable.com/appNMgC4snjFIJQ0X/shrV1HBbujo5ZZbzN). We then get in touch via email to describe the next steps in the process and to make sure it’s a good fit for what they want to achieve.

If everything seems right, we’ll set up the Clubs page and go through the workflow with the Club Lead to ensure that the Club and all its participating authors are credited on the reviews they author together.

You might start a PREreview Club based on affinity, geography, or language. You might also create a Club for your class, lab, institution, or organization. You might even start a Club for your friends who love collaborative preprint review!

You can check out our PREreview Clubs onboarding document [here](https://zenodo.org/records/10210085) to learn more.

You can also join an existing Club, take a look here for a [list of our current PREreview Clubs](https://prereview.org/clubs). Please note that some are open to others to join and will include a ‘Join the club’ button, whereas others may be closed. 
