# Using Zoom (or other video conferencing software)

Zoom is a fairly intuitive and simple tool to use. That said, here are some tips based on what we have learned over the years:

 - Ensure that all speakers join 10 minutes early to do a ‘tech-check’. This means ensuring that everyone’s audio and video settings are correct, and you may want to practice screen sharing to make sure that it is set up properly. 
 - Make sure when screen sharing your presentation that the audience can see the correct screen and that they see it full screen. Also, ensure you have it set up so that you are able to see any notes you need. 
 - In the Zoom meeting settings, you can choose to do things like allow Q&A as well as chat, and you may also wish to mute participants upon entry to cut down on background noise. 
 - Make sure recording is switched on (if you are recording) and that in the Zoom settings, recording notifications are turned on for all participants so that everyone is aware they are being recorded and can choose to leave the call if they do not give their consent.
 - For events where the audience are not native English speakers, it can be useful to switch on the live captions during the meeting (please note this will only work in English and will not be perfect).
 - Make sure you have someone to manage the Q&A and the chat so that the speakers can focus on presenting. 
 - When not speaking, it’s good practice to mute your microphone to cut down on any background noise. 
 - A good tip is to make sure that you have the links to any resources you plan to share ready in advance, so you can simply copy/paste across to the chat.
 - You can also set up polls in advance to engage your audience and get some quick feedback. 
 - If you are running a meeting with breakout rooms, you can let Zoom randomly allocate people during the meeting, or if you want people in set groups, then it’s good to pre-assign participants to rooms in advance.

Zoom also has a lot of helpful online resources if you want to read more. They also run online training sessions fairly regularly and have several quick walkthrough videos. Here are some helpful guides:

 - [Getting started guide for new users](https://support.zoom.us/hc/en-us/articles/360034967471-Getting-started-guide-for-new-users)
 - [Managing breakout rooms](https://support.zoom.us/hc/en-us/articles/206476313-Managing-breakout-rooms)
 - [Assigning polls to specific meetings](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0066150)
 - [Conducting quizzes in meetings](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0066403)
 - [Change your language on Zoom](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0062475) 
