# Using Slack

At PREreview, we regularly use [Slack](https://slack.com/) to communicate internally and also externally with our community members. In Slack, conversations are organized into channels depending on the topic or group of people involved. We have a private [#prereview-champions-2026](https://prereviewcommunity.slack.com/archives/C0A8747507J) channel that you have been added to upon joining the Champions Program. We encourage you to use this channel to post questions to the team, get feedback on your plans, collaborate, problem-solve, or just chat about things that are going on in your life. 

You can use Slack in a browser and download it to your desktop or phone. Here are some tips for using Slack: 

 - When setting up your profile, please choose a username that will be easy to identify you by (your email address will not be shared), an appropriate profile picture, and make sure that your account is set to the correct time zone so that Slack doesn’t notify you at times when you are not available.
 - To configure your notifications, simply click your name at the top left of the page and select ‘Preferences’ from the dropdown list. In the notifications section, you can then choose times when you don’t want to be disturbed as well as set alerts for certain channels or keywords.
 - You can also set a status to show when you’re on holiday, sick, or otherwise busy so people know not to message you directly.
 - Use threads to continue a conversation. You can reply directly to a message in the channel, which will create a thread, making it easier to follow the conversation.
 - Don’t feel you need to respond immediately to a message. Although Slack is a messaging application, interactions do not need to be synchronous, especially when we are working across a wide range of time zones.
 - Please respect the shared space and the other members of the channel, including in any private communication. Please abide by our [Code of Conduct](https://prereview.org/code-of-conduct) at all times. 

For more information, please refer to the Center for Scientific Collaboration and Community Engagement. (2023) Slack quick start guide v3. Woodley, Maya and Pratt. doi: [https://zenodo.org/records/10411198).
